# Generated by Django 3.0.5 on 2020-04-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200430_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nr_rg',
            field=models.CharField(default='0', max_length=15, verbose_name='Número do RG'),
            preserve_default=False,
        ),
    ]
