# Generated by Django 3.0.5 on 2020-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_nr_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='Não informado', max_length=45, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nm_mae',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nome da mãe'),
        ),
    ]
